{% set name = "jinja2-git" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f0fbe896fc5116276b8a47dfc8bc52fd5e9f5ee54deee71dcb7986b03cf7973

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.2.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - jinja2 >=2.10,<4.0

test:
  imports:
    - jinja2_git
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wemake-services/jinja2-git
  summary: Jinja2 extension to handle git-specific things
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
